version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - FLASK_APP=target/aplicacao/aplicacao.py
      - FLASK_ENV=development
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - APPLY_TO_ALL=True
    container_name: target
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - 5000:5000  
  

  mongodb:
    image: mongo:4.4.14
    container_name: target_db
    volumes:
      - ./:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_COLLECTION: board
    restart: unless-stopped
    ports:
      - 27017:27017
    
