version: "3"

services:
  web:
    build: .
    image: target_data
    volumes:
      - ./:/app
    container_name: target
    tty: true # docker run -t
    stdin_open: true # docker run -i
    command: bash
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      -  DB_HOST=mongodb
    ports:
      - 5000:5000
    networks:
      - target_data_net 

  mongodb:
    image: mongo:4.4.14
    container_name: mongodb
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - target_data_net 
networks:
  target_data_net:
    driver: bridge
