version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    container_name: target
    command: python -u /app/target/aplicacao/aplicacao.py
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - 5000:5000  
  

  mongodb:
    image: mongo:4.4.14
    container_name: target_db
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 27017:27017
    
