version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    container_name: target
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - 5000:5000  
  

  mongodb:
    image: mongo:4.4.14
    container_name: target_db
    volumes:
      - ./:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_COLLECTION: board
    restart: unless-stopped
    ports:
      - 27017:27017
    
